### ISSUE TITLE
Fix data not displaying on certain modals/cards

### ISSUE THREAD

**Issue by BlueishLeaf** [PAKDProject/linkedout-frontend#78]
### User Dashboard
- Active jobs
  - Payment
  - Date Accepted
  - Location
- Posted jobs
  - Date Posted
  - Location

**Comment by BlueishLeaf** [comment]
Might be more though

**Comment by dairefinn** [comment]
Posted jobs doesn't show the date because it's not a part of the object inside the user
![postederror](https://user-images.githubusercontent.com/23464903/53418237-3c0cdc00-39cf-11e9-9708-174b0398af7a.PNG)

**Comment by dairefinn** [comment]
Payment isnt a property of the active job present. May be an error during creation/accepting or just with that job
![payment](https://user-images.githubusercontent.com/23464903/53423732-c65a3d80-39d9-11e9-88a0-710a1f989af8.PNG)

**Comment by dairefinn** [comment]
I think is fix
